name: inki
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  adobe_xd: ^1.1.0+1
  http: ^0.12.2
  provider: ^4.3.2+2
  device_info: ^0.4.2+8
  package_info: ^0.4.3
  connectivity: ^0.4.9+3
  data_connection_checker: ^0.3.4
  cached_network_image: ^2.3.2+1
  google_fonts: ^1.1.2
  flare_flutter: ^2.0.6
  carousel_slider: ^3.0.0
  flutter_screenutil: 4.0.3+2
  flutter_rating_bar: ^3.0.1+1
  confetti: ^0.5.4+1
  responsive_framework: ^0.0.14
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12
  path_provider: ^1.3.0
  flutter_svg: ^0.19.1
  fluttertoast: ^7.1.8
  flutter_swiper: ^1.1.6
  usb_serial: ^0.2.4
  webview_flutter: 0.3.18+1
  qr_flutter: ^4.0.0
  flutter_inappwebview: 5.1.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  hive_generator: ^0.8.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
